version: '3.8'

services:
  source_db:
    image: postgres:13
    container_name: source_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=source_data
    ports:
      - "5431:5432"
    volumes:
      - ./seeds/source_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d source_data"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - etl_network

  data_warehouse:
    image: postgres:13
    container_name: data_warehouse
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dwh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dwh"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - etl_network

  mock_api:
    build: ./mock_api
    container_name: mock_api
    ports:
      - "8000:8000"
    networks:
      - etl_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - etl_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  init-minio:
    image: minio/mc
    container_name: init-minio
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - etl_network
    volumes:
      - ./seeds/s3_data:/src
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/raw-data || true;
      mc cp /src/inventory.csv myminio/raw-data/;
      exit 0;
      "

  airflow_web:
    image: apache/airflow:2.7.1
    container_name: airflow_web
    # This block ensures dbt is installed every time the container starts
    command: >
      bash -c "pip install --no-cache-dir dbt-postgres &&
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
      airflow standalone"
    user: "${AIRFLOW_UID:-50000}:0"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt_project:/opt/airflow/dbt_project
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_CONN_DATA_WAREHOUSE=postgres://user:password@data_warehouse:5432/dwh
      - AIRFLOW_CONN_SOURCE_DB=postgres://user:password@source_db:5432/source_data
      - AIRFLOW_CONN_AWS_DEFAULT=aws://minioadmin:minioadmin@?endpoint_url=http%3A%2F%2Fminio%3A9000
    depends_on:
      source_db:
        condition: service_healthy
      data_warehouse:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - etl_network

networks:
  etl_network: 
    driver: bridge

volumes:
  minio_data: